[package]
name = "pac-man"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = { git="https://github.com/ggez/ggez", branch="devel"}
nalgebra = "0.32.2"
oorandom = "11.1.3"
getrandom = "0.2.9"